<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#2.1.-Numpy-ndarray---создание" data-toc-modified-id="2.1.-Numpy-ndarray---создание-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>2.1. Numpy ndarray - создание</a></span></li><li><span><a href="#2.2.-Numpy-ndarray---индексы" data-toc-modified-id="2.2.-Numpy-ndarray---индексы-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>2.2. Numpy ndarray - индексы</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.3.-Numpy-ndarray---элементарные-операции-с-массивами" data-toc-modified-id="2.3.-Numpy-ndarray---элементарные-операции-с-массивами-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>2.3. Numpy ndarray - элементарные операции с массивами</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.4.-Numpy---основные-функции." data-toc-modified-id="2.4.-Numpy---основные-функции.-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>2.4. Numpy - основные функции.</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.5.-Numpy---I/O." data-toc-modified-id="2.5.-Numpy---I/O.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>2.5. Numpy - I/O.</a></span></li></ul></div>

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt

# 2.1. Numpy ndarray - создание

Numpy - библиотека для векторизованных вычислений в Python'e. Написана на C. Основной объект в numpy - nddarray, который располагается напрерывно в памяти и позволяет производить быстрые вычисления.

In [2]:
import numpy as np

In [3]:
%%timeit
[[i**2 for i in list(range(100))]]

24.4 µs ± 360 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [4]:
%%timeit
a = np.array(list(range(100)))
a * a

8.5 µs ± 225 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
%%timeit
a = np.array(list(range(100)))
a ** 2

8.86 µs ± 58.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Создание массива

In [9]:
a = np.array([1, 2, 3, 4])

In [10]:
a.shape

(4,)

Shape - кортеж, который указывает число элементов в каждом измерении. 

In [11]:
a = np.array([[1, 2], [3, 4]])

In [12]:
a.size

4

In [13]:
a.shape

(2, 2)

In [14]:
a.dtype

dtype('int64')

In [15]:
a.itemsize

8

In [16]:
a.nbytes

32

In [16]:
a.strides

(16, 8)

In [17]:
a.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

In [18]:
a.reshape(4, 1).strides

(8, 8)

In [20]:
a.reshape(1, 4).strides

(32, 8)

In [19]:
a.reshape(1, 3)

ValueError: cannot reshape array of size 4 into shape (1,3)

In [21]:
a.reshape(1, -1)

array([[1, 2, 3, 4]])

In [22]:
a.reshape(1, -1).shape

(1, 4)

При желании, можно использовать np.size(np.object) и np.shape(np.object):

In [23]:
np.size(a)

4

In [24]:
np.shape(a)

(2, 2)

При необходимости, не стоит принебрегать встроенной справкой:

In [26]:
np.array()

И специальными функциями numpy:

In [27]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArray.__new_

и IPython:

In [28]:
np.con*?

In [30]:
a

array([[1, 2],
       [3, 4]])

In [31]:
a[0, 0] = 100

In [32]:
a

array([[100,   2],
       [  3,   4]])

**Создание массивов**

Создавать из списков мы уже умеем:

In [36]:
np.array([1, 2, 3, 4], dtype=np.int16)

array([1, 2, 3, 4], dtype=int16)

In [42]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [47]:
np.linspace(0, 1, 25, endpoint=False)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96])

In [48]:
np.linspace(0, 1, 26)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  ])

In [53]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
np.ones(3)

array([1., 1., 1.])

In [54]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

** Случайные массивы **

на интервале [0,1]:

In [57]:
np.random.rand(3, 2)

array([[0.50755507, 0.0211933 ],
       [0.43352176, 0.44631306],
       [0.23881999, 0.83024573]])

Нормально распределенные:

In [58]:
np.random.randn(3, 2)

array([[ 0.53942869,  1.52676162],
       [-3.2771929 , -1.84856065],
       [ 0.67212494, -1.49297925]])

-- N: иногда полезно получить случайное целое число:

In [59]:
np.random.randint(2, 10)

6

# 2.2. Numpy ndarray - индексы

Отдельно рассмотрим 1-мерный и многомерные массивы.

In [61]:
t = np.random.rand(3,)

In [62]:
t

array([0.92284354, 0.13187791, 0.98859553])

Для одномерного массива получим сразу элемент, который находится по данному индексу. Для n-мерного массива подобная индексация вернет массив размера n-1.

In [72]:
t = np.random.rand(3, 5, 10)
t

array([[[0.69731848, 0.64030008, 0.61079581, 0.48224294, 0.06458627,
         0.26639941, 0.76641551, 0.40138783, 0.73152747, 0.84313985],
        [0.97797907, 0.85665519, 0.63556707, 0.79987186, 0.16574947,
         0.02547515, 0.92831737, 0.48301457, 0.39218194, 0.83930573],
        [0.11483626, 0.88628341, 0.76875381, 0.39737809, 0.09770546,
         0.79446101, 0.77356784, 0.1583002 , 0.65950121, 0.5806056 ],
        [0.86257477, 0.44914192, 0.31568098, 0.61964859, 0.18189093,
         0.21816502, 0.83891091, 0.18980057, 0.45863056, 0.22532233],
        [0.8494496 , 0.03878267, 0.87599246, 0.82497679, 0.34992698,
         0.67307427, 0.0030774 , 0.01793643, 0.64514203, 0.85600529]],

       [[0.98521239, 0.99028519, 0.01488255, 0.53078837, 0.10039138,
         0.50710218, 0.89080772, 0.02688303, 0.25038762, 0.09038133],
        [0.46673026, 0.85016574, 0.96152402, 0.16083919, 0.39644306,
         0.20182766, 0.30553636, 0.33448311, 0.82766318, 0.97897464],
        [0.94954394, 0.43

In [76]:
t.shape

(3, 5, 10)

In [78]:
t[0, 1, :]

array([0.97797907, 0.85665519, 0.63556707, 0.79987186, 0.16574947,
       0.02547515, 0.92831737, 0.48301457, 0.39218194, 0.83930573])

In [79]:
np.random.rand(3, 5, 10)[1].shape

(5, 10)

In [80]:
np.random.rand(3, 5)[1].shape

(5,)

Можно использовать ':' вместо индекса:

In [99]:
A = np.random.rand(3, 5)

In [100]:
A

array([[0.08110108, 0.33815273, 0.27318236, 0.37236351, 0.93002092],
       [0.37714301, 0.25988167, 0.26793939, 0.29752658, 0.16676428],
       [0.17880017, 0.52515722, 0.41372529, 0.46121241, 0.55767201]])

In [101]:
A[0, :]

array([0.08110108, 0.33815273, 0.27318236, 0.37236351, 0.93002092])

In [102]:
A[:, 0]

array([0.08110108, 0.37714301, 0.17880017])

Поддерживается стандартный протокол - python slicing syntax ([lower:upper:step]) :

In [103]:
A[0, :]

array([0.08110108, 0.33815273, 0.27318236, 0.37236351, 0.93002092])

In [104]:
A[0, :][0:4:2]

array([0.08110108, 0.27318236])

In [105]:
a = A[0, :]

In [106]:
a

array([0.08110108, 0.33815273, 0.27318236, 0.37236351, 0.93002092])

Операция slicing создает т.н. view - то есть данные не копируются, поэтому исходный объект по адресу - mutable.

In [114]:
A[0,:][0:4:2]

array([0.08110108, 0.27318236])

In [115]:
A[0,:][0:4:2] = [1.0, 2.5]

In [116]:
A

array([[1.        , 0.33815273, 2.5       , 0.37236351, 0.93002092],
       [0.37714301, 0.25988167, 0.26793939, 0.29752658, 0.16676428],
       [0.17880017, 0.52515722, 0.41372529, 0.46121241, 0.55767201]])

Параметры для slicing могут пропускаться:

In [117]:
A[0,:][0:4:2]

array([1. , 2.5])

In [118]:
A[0,:][0:4]

array([1.        , 0.33815273, 2.5       , 0.37236351])

In [119]:
A[0,:][:3]

array([1.        , 0.33815273, 2.5       ])

In [120]:
A[0,:][3:]

array([0.37236351, 0.93002092])

In [122]:
A[0,:]

array([1.        , 0.33815273, 2.5       , 0.37236351, 0.93002092])

In [121]:
A[0,:][::-1]

array([0.93002092, 0.37236351, 2.5       , 0.33815273, 1.        ])

In [129]:
A[0,:]

array([1.        , 0.33815273, 2.5       , 0.37236351, 0.93002092])

In [128]:
A[0,:][:-3]

array([1.        , 0.33815273])

In [134]:
A[0,:][-3:]

array([2.5       , 0.37236351, 0.93002092])

** Fancy Indexing **

Этим термином обозначается индексирование с помощью массивов (или иных итерируемых конструкций).

In [135]:
A

array([[1.        , 0.33815273, 2.5       , 0.37236351, 0.93002092],
       [0.37714301, 0.25988167, 0.26793939, 0.29752658, 0.16676428],
       [0.17880017, 0.52515722, 0.41372529, 0.46121241, 0.55767201]])

In [137]:
row_indices = [1, 2]
A[row_indices]

array([[0.37714301, 0.25988167, 0.26793939, 0.29752658, 0.16676428],
       [0.17880017, 0.52515722, 0.41372529, 0.46121241, 0.55767201]])

In [138]:
col_indices = [1, -1]
A[row_indices, col_indices]

array([0.25988167, 0.55767201])

Возможно Булево индексирование (**Boolean indexing**):

In [139]:
B = np.array([n for n in range(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [143]:
B[B > 2]

array([3, 4])

In [151]:
row_mask = np.array([1, 0, 1, 0, 0], dtype=bool)
B[row_mask]

array([0, 2])

Это очень удобно, как вы наверняка догадались, если мы хотим отобрать данные, отвечающие определенным условиям:

In [153]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [155]:
mask = (5 < x) * (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [156]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [157]:
a = np.array([[1, 2], [3, 4]])

In [169]:
a * (a > 1)

array([[0, 2],
       [3, 4]])

In [170]:
a[a > 0]

array([1, 2, 3, 4])

Получить список индексов элементов, отвечающих заданной маске, можно с помощью **which**:

In [171]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [172]:
x[indices]

array([5.5, 6. , 6.5, 7. ])

**take** еще одна конструкция выбора элементов массива:

In [173]:
v = np.arange(-3, 3)
row_indices = [1, 3, 5]

In [174]:
v

array([-3, -2, -1,  0,  1,  2])

In [175]:
v[row_indices]

array([-2,  0,  2])

In [176]:
v.take(row_indices)

array([-2,  0,  2])

In [177]:
np.take(v, row_indices)

array([-2,  0,  2])

** choices ** - полезная функция для выбора элеметов из нескольких массивов:

In [178]:
which = [1, 0, 1, 0]
choices = [[-1, -2, -3, -4], [1, 2, 3, 4]]
np.choose(which, choices)

array([ 1, -2,  3, -4])

** compress ** - альтернативой Булевому индексированию:

In [179]:
a = np.array([[1, 2], [3, 4], [5, 6]])
np.compress([False, True, True], a, axis=0)

array([[3, 4],
       [5, 6]])

## TLDR:
* для доступа к элементам массива пользуйтесь slicing и помните, что slicing создает view, а значит исходный массив может быть изменен.

# 2.3. Numpy ndarray - элементарные операции с массивами

** Broadcasting **

Концепеция broadcasting является ключевой для понимания операций с массивами. Обычно, операции с массивами производятся поэлементно. 

In [180]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [183]:
a / b

array([0.5, 1. , 1.5])

Что, если массивы разного размера? Начнем с простого - скаляр и вектор:

In [184]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

Все просто - скаляр словно "вырастает" (broadcasted) до размеров вектора и производится поэлементная операция (разумеется, это умозрительная аналогия - новый вектор из 2 не создается!).

Общее правило таково:

операция может произведена если размерность "крайних" осей массивов совпадает (trailing dimension), либо один из элементов является скаляром.

Пример из оффициальной документации:

In [187]:
'''

Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

'''
pass

а вот эти операции дадут вам ошибку:

In [188]:
'''
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
'''
pass

In [189]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

print(x.shape)

print(y.shape)

x + y

(4,)
(5,)


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [191]:
print(xx.shape)
print(y.shape)
print((xx + y).shape)
print(xx + y)

print('-------')

print(x.shape)
print(z.shape)
print((x + z).shape)
print(x + z)

(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
-------
(4,)
(3, 4)
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Классный пример из официальной документации:

In [193]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [196]:
a[:, np.newaxis]

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [197]:
a[:, np.newaxis].shape

(4, 1)

** Операции вида "массив - скаляр" **

In [198]:
A

array([[1.        , 0.33815273, 2.5       , 0.37236351, 0.93002092],
       [0.37714301, 0.25988167, 0.26793939, 0.29752658, 0.16676428],
       [0.17880017, 0.52515722, 0.41372529, 0.46121241, 0.55767201]])

In [199]:
A + 2

array([[3.        , 2.33815273, 4.5       , 2.37236351, 2.93002092],
       [2.37714301, 2.25988167, 2.26793939, 2.29752658, 2.16676428],
       [2.17880017, 2.52515722, 2.41372529, 2.46121241, 2.55767201]])

** Операции вида "массив - массив" **

Производятся поэлементно с учетом правил broadcasting:

In [200]:
A * A

array([[1.        , 0.11434727, 6.25      , 0.13865458, 0.86493891],
       [0.14223685, 0.06753848, 0.07179152, 0.08852207, 0.02781033],
       [0.0319695 , 0.2757901 , 0.17116862, 0.21271689, 0.31099807]])

In [201]:
A / A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

** Матричные операции**

In [202]:
A = np.random.rand(3,3)

In [203]:
np.dot(A, A)

array([[0.17256283, 0.14299063, 0.23531004],
       [0.34006011, 0.22066009, 0.33606892],
       [0.31086579, 0.23436474, 0.35118879]])

In [204]:
v = np.random.randn(3)

In [205]:
v

array([1.40744903, 0.04996093, 0.01032259])

In [209]:
v[:, np.newaxis]

array([[1.40744903],
       [0.04996093],
       [0.01032259]])

In [206]:
A * v

array([[1.31748298e-01, 5.32696802e-03, 3.98210460e-03],
       [1.01586098e+00, 1.78107476e-02, 6.96449779e-04],
       [3.16842151e-01, 1.23034972e-02, 5.13782127e-03]])

In [207]:
np.dot(A, v)

array([0.14105737, 1.03436818, 0.33428347])

In [208]:
np.dot(A, v[:, np.newaxis])

array([[0.14105737],
       [1.03436818],
       [0.33428347]])

In [210]:
np.dot(v[np.newaxis, :], A)

array([[0.17013263, 0.17041879, 0.55145445]])

In [211]:
np.dot(v, v)

1.983515434999847

Если хочется использовать по умолчанию операции из матричной алгебры, то можно использовать конструктор matrix().

In [212]:
M = np.matrix(A)

In [213]:
v1 = np.matrix(v).T

In [214]:
M.shape

(3, 3)

In [215]:
v1.shape

(3, 1)

In [218]:
v1.T * v1

matrix([[1.98351543]])

In [219]:
M * v1

matrix([[0.14105737],
        [1.03436818],
        [0.33428347]])

** Преобразование массивов**

In [221]:
A.T

array([[0.09360786, 0.72177461, 0.22511803],
       [0.10662267, 0.35649349, 0.24626236],
       [0.3857659 , 0.06746849, 0.49772581]])

** reshape **

In [222]:
a

array([ 0., 10., 20., 30.])

In [223]:
a = a.reshape((2, 2))

In [225]:
a.reshape(2, -1)

array([[ 0., 10.],
       [20., 30.]])

** resize **

In [226]:
a = np.arange(4)

In [227]:
a.resize((8,))

In [228]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

** repeat **

In [232]:
a = np.array([[1, 2], [3, 4]])
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [233]:
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

** concatenate **

In [234]:
a

array([[1, 2],
       [3, 4]])

In [235]:
b = np.array([[5, 6]])

In [236]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [237]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

** hstack **

Название говорит само за себя - horizontal stack.

In [238]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [239]:
a.shape

(2, 2)

In [240]:
b.T.shape

(2, 1)

** vstack **

In [241]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [242]:
a.shape

(2, 2)

In [243]:
b.shape

(1, 2)

** Копии и view **

Мы помним, что очень важно различать копирование объекта и присваивание новой ссылки на объект. Numpy в этом смысле не отличается от списков:

In [252]:
A = np.array([[1, 2], [3, 4]])

In [245]:
B = A

In [246]:
B[0, 0] = 10

In [247]:
A

array([[10,  2],
       [ 3,  4]])

Если это не тот тип поведения, который нам нужен - следует использовать np.copy():

In [252]:
A = np.array([[1, 2], [3, 4]])

In [253]:
B = np.copy(A)

In [254]:
B[0, 0] = 100

In [255]:
A

array([[1, 2],
       [3, 4]])

Важно помнить, что если вы используете view массива, то копии вы не создаете!

In [256]:
a = np.arange(10)

In [257]:
b = a[::2]

In [258]:
np.may_share_memory(a, b)

True

In [259]:
c = a[::2].copy()
np.may_share_memory(a, c)

False

In [260]:
d = a.T
np.may_share_memory(a, d)

True

## TLDR:
* следует отличать копию массива и view;
* при осуществлении операций помните про правила broadcasting;
* запомните hstack и vstack.

# 2.4. Numpy - основные функции.

** Встроенные функции массива **

In [261]:
m = np.random.rand(3,3)

In [262]:
m.sum()

3.757706523036056

In [263]:
m.max()

0.891675341757194

** Всегда используйте встроенные функции! **

In [269]:
a = np.random.rand(100000)

In [270]:
%timeit -n 1000 max(a)

11.3 ms ± 1.57 ms per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [271]:
%timeit -n 1000 a.max()

45.8 µs ± 3.13 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [272]:
%timeit -n 1000 sum(a)

17 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [273]:
%timeit -n 1000 a.sum()

36.4 µs ± 2.09 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Просто считать сумму элементов матрицы или находить максимальный элемент не так интересно, и тут нам помогают axis:

In [274]:
m

array([[0.22269992, 0.89167534, 0.56979494],
       [0.01670116, 0.04541208, 0.61467689],
       [0.48989744, 0.48938569, 0.41746307]])

In [275]:
m.sum(axis=0)

array([0.72929852, 1.42647311, 1.6019349 ])

In [276]:
m.sum(axis=1)

array([1.6841702 , 0.67679013, 1.39674619])

In [277]:
m.max(axis=0)

array([0.48989744, 0.89167534, 0.61467689])

Очень полезно произведение всех элементов:

In [278]:
m.prod(axis=1)

array([0.11314761, 0.00046619, 0.10008627])

Кумулятивная сумма элементов:

In [279]:
a.cumsum() * 100

array([7.99173691e+01, 1.53962191e+02, 2.04393583e+02, ...,
       4.97710549e+06, 4.97713204e+06, 4.97717532e+06])

Кумулятивное произведение:

In [280]:
a.cumprod()

array([0.79917369, 0.59174673, 0.29842612, ..., 0.        , 0.        ,
       0.        ])

**Простые статистики**

**Среднее**

In [281]:
m.mean(axis=0)

array([0.24309951, 0.47549104, 0.5339783 ])

In [282]:
np.mean(m, axis=0)

array([0.24309951, 0.47549104, 0.5339783 ])

In [283]:
np.mean(a)

0.4977175322307717

In [284]:
a.mean()

0.4977175322307717

**Медиана**

In [285]:
np.median(m, axis=0)

array([0.22269992, 0.48938569, 0.56979494])

In [286]:
np.median(a)

0.49523055044361725

** Дисперсия **

In [287]:
np.std(m, axis=0)

array([0.19371936, 0.3456252 , 0.0844016 ])

In [288]:
m.std(axis=0)

array([0.19371936, 0.3456252 , 0.0844016 ])

In [289]:
np.var(a)

0.0835405692409599

In [290]:
a.var()

0.0835405692409599

** Сортировка **

In [271]:
np.sort(a)

array([2.80374084e-06, 2.59103536e-05, 4.30852707e-05, ...,
       9.99993295e-01, 9.99996412e-01, 9.99999120e-01])

Функция выше возвращает отсортированную копию массива. Если нужна сортировка in-place:

In [272]:
a.sort()

In [273]:
a = np.random.rand(100000)

Также иногда бывает полезно получить только список индексов в правильном порядке:

In [274]:
np.argsort(a)

array([83549, 76609, 81507, ..., 37958,  4533,  3793])

In [275]:
np.argmax(a)

3793

In [276]:
np.argmin(a)

83549

In [277]:
np.nonzero(a)

(array([    0,     1,     2, ..., 99997, 99998, 99999]),)

** Функции для работы с матрицами **

In [278]:
m

array([[0.46289232, 0.84718667, 0.67802359],
       [0.36786229, 0.13798301, 0.40280945],
       [0.93129709, 0.67316279, 0.41922982]])

In [279]:
np.diag(m)

array([0.46289232, 0.13798301, 0.41922982])

In [280]:
m.diagonal()

array([0.46289232, 0.13798301, 0.41922982])

Для целого класса функций из линейной алгебры есть свой суб-модуль np.linalg.

http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [281]:
MM = np.random.randn(9, 6)

In [282]:
U, s, V = np.linalg.svd(MM, full_matrices=False)
U.shape, V.shape, s.shape

((9, 6), (6, 6), (6,))

In [283]:
S = np.diag(s)
np.allclose(MM, np.dot(U, np.dot(S, V)))

True

** Векторизация кода **

В numpy есть встроенная функция vectorize, которая "автоматически" векторизует вашу функцию:

In [286]:
def heavyside(x):
    if x >= 0:
        return 1
    else:
        return 0

In [287]:
heavyside(np.array([-3, -2, -1, 0, 1, 2, 3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [288]:
heavyside_vec = np.vectorize(heavyside)

In [290]:
heavyside_vec(np.array([-3, -2, -1, 0, 1, 2, 3]))

array([0, 0, 0, 1, 1, 1, 1])

Тем не менее, лучше сразу пишите так:

In [291]:
def heavyside(x):
    return 1 * (x >= 0)

In [292]:
heavyside(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

In [293]:
np.array([-3,-2,-1,0,1,2,3]) >= 0

array([False, False, False,  True,  True,  True,  True])

In [294]:
1 * (np.array([-3,-2,-1,0,1,2,3]) >= 0)

array([0, 0, 0, 1, 1, 1, 1])

** Условные выражения **

Как вы уже поняли, для вектора конструкция типа if (vector) не подходит.

In [295]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

no element in M is larger than 5


In [296]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

all elements in M are not larger than 5


## TLDR:
- всегда используйте встроенные в np функции;
- векторизуйте везде, где это возможно!

# 2.5. Numpy - I/O.

В данном случае у нас на выбор 2 опции - либо формат numpy, либо просто текстовый файл.

In [291]:
np.save("random.npy", M)

In [292]:
!ls

README.md          matplotlib.ipynb   pandas.ipynb
axis.png           movie_metadata.csv random.csv
lecture01.pdf      numpy.ipynb        random.npy


In [293]:
np.load("random.npy")

array([[0.09360786, 0.10662267, 0.3857659 ],
       [0.72177461, 0.35649349, 0.06746849],
       [0.22511803, 0.24626236, 0.49772581]])

In [294]:
np.savetxt('random.csv', M, delimiter='\t')

In [301]:
! cat random.csv

9.939709930102422764e-01	5.478388389420346671e-01	7.302345718427495358e-01
2.798428506475958422e-02	8.635912766427542575e-01	9.986307593601151389e-01
3.253098239428288130e-01	8.502608344688427078e-01	6.114921194053263287e-01


In [295]:
np.loadtxt('random.csv')

array([[0.09360786, 0.10662267, 0.3857659 ],
       [0.72177461, 0.35649349, 0.06746849],
       [0.22511803, 0.24626236, 0.49772581]])